# Generated by Django 3.2 on 2023-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformaDoKursow', '0002_auto_20231103_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
