# Generated by Django 3.2 on 2023-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformaDoKursow', '0003_course_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invitation_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
