# Generated by Django 3.2 on 2023-11-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformaDoKursow', '0005_remove_course_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='platformaDoKursow.course'),
        ),
    ]
