# Generated by Django 3.2 on 2023-11-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformaDoKursow', '0006_alter_chapter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platformaDoKursow.chapter'),
        ),
    ]
