# Generated by Django 3.2 on 2023-11-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformaDoKursow', '0007_alter_quiz_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='platformaDoKursow.course'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user_id', 'course_id')},
        ),
    ]
