# Generated by Django 3.2 on 2023-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformaDoKursow', '0008_auto_20231113_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
